kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: easyshop-hpa
  namespace: easyshop-ns

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: easyshop-deployment

  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
